language: php
dist: trusty
php: [5.5, 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, hhvm]
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - composer selfupdate
  - composer update
script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/behat -c examples/json/behat.yml
  - vendor/bin/behat -c examples/xml/behat.yml
